export const QKeys ={
    GET_EVENTS: 'GET_EVENTS',
    GET_EVENT_BY_INDEX: 'GET_EVENT_BY_INDEX',
    GET_EVENT: 'GET_EVENT',
    CREATE_EVENT: 'CREATE_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT'
}